<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MAASDS02610A" name="com.rashtriya.testcases.TC000_Merger" tests="9" failures="0" timestamp="2022-09-20T11:12:36 IST" time="1135.943" errors="1">
  <testcase name="adminLoginCheck" time="62.081" classname="com.rashtriya.testcases.TC000_Merger">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.ui.Select.<init>(Select.java:44)
at com.rashtriya.pages.DetailsPage_Basic.selectDropDownUsingVisibleText(DetailsPage_Basic.java:91)
at com.rashtriya.testcases.TC000_Merger.adminLoginCheck(TC000_Merger.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- adminLoginCheck -->
  <system-out/>
  <testcase name="adminLoginCheck" time="133.857" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
  <testcase name="adminLoginCheck" time="133.277" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
  <testcase name="adminLoginCheck" time="123.077" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
  <testcase name="adminLoginCheck" time="134.918" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
  <testcase name="adminLoginCheck" time="132.755" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
  <testcase name="adminLoginCheck" time="139.537" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
  <testcase name="adminLoginCheck" time="132.001" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
  <testcase name="adminLoginCheck" time="144.440" classname="com.rashtriya.testcases.TC000_Merger"/>
  <system-out/>
</testsuite> <!-- com.rashtriya.testcases.TC000_Merger -->
